[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "kaihoplots"
version = "0.0.1"
description = "Kaiho Stylesheet for matplotlib"
long_description_content_type = "text/markdown"

[tool.setuptools.package-data]
kaihoplots = ["*.mplstyle"]
