[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "kaihoplots"
version = "0.0.1"
description = "Kaiho Stylesheet for matplotlib"
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.package-data]
kaihoplots = ["*.mplstyle"]
