[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "kaihoplots"
version = "0.0.1"
description = "Kaiho Stylesheet for matplotlib"

[tool.setuptools.package-data]
kaihoplots = ["styles/**/*.mplstyle"]
