on:
  release:
    types:
      - released

jobs:
  test:
    uses: ./.github/workflows/tester.yaml

  deploy:
    runs-on: ubuntu-latest
    depends-on: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
          cache: 'pip'
      - name: Build and deploy
        run: |
          python -m pip install --upgrade build
          python -m build
          python -m twine upload --repository pypi dist/*
